/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateBrandRequest } from '../model/models';
import { CreatedBrandResponse } from '../model/models';
import { Get400Response } from '../model/models';
import { GetAllBrandResponse } from '../model/models';
import { GetBrandResponse } from '../model/models';
import { Result } from '../model/models';
import { UpdateBrandRequest } from '../model/models';
import { UpdateBrandResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add5RequestParams {
    createBrandRequest: CreateBrandRequest;
}

export interface Delete4RequestParams {
    id: number;
}

export interface GetBrandRequestParams {
    id: number;
}

export interface Update4RequestParams {
    id: number;
    updateBrandRequest: UpdateBrandRequest;
}


export interface BrandControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add5(requestParameters: Add5RequestParams, extraHttpRequestParams?: any): Observable<CreatedBrandResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete4(requestParameters: Delete4RequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
*/
    getAll5(extraHttpRequestParams?: any): Observable<Array<GetAllBrandResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getBrand(requestParameters: GetBrandRequestParams, extraHttpRequestParams?: any): Observable<GetBrandResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    update4(requestParameters: Update4RequestParams, extraHttpRequestParams?: any): Observable<UpdateBrandResponse>;

}
