/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCarRequest } from '../model/models';
import { CreatedCarResponse } from '../model/models';
import { Get400Response } from '../model/models';
import { GetAllCarResponse } from '../model/models';
import { GetCarResponse } from '../model/models';
import { Result } from '../model/models';
import { UpdateCarRequest } from '../model/models';
import { UpdateCarResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add4RequestParams {
    createCarRequest: CreateCarRequest;
}

export interface Delete3RequestParams {
    id: number;
}

export interface GetCarRequestParams {
    id: number;
}

export interface Update3RequestParams {
    id: number;
    updateCarRequest: UpdateCarRequest;
}


export interface CarControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add4(requestParameters: Add4RequestParams, extraHttpRequestParams?: any): Observable<CreatedCarResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete3(requestParameters: Delete3RequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
*/
    getAll4(extraHttpRequestParams?: any): Observable<Array<GetAllCarResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCar(requestParameters: GetCarRequestParams, extraHttpRequestParams?: any): Observable<GetCarResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    update3(requestParameters: Update3RequestParams, extraHttpRequestParams?: any): Observable<UpdateCarResponse>;

}
