/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateFuelRequest } from '../model/models';
import { CreatedFuelResponse } from '../model/models';
import { Get400Response } from '../model/models';
import { GetAllFuelResponse } from '../model/models';
import { GetFuelResponse } from '../model/models';
import { Result } from '../model/models';
import { UpdateFuelRequest } from '../model/models';
import { UpdateFuelResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add3RequestParams {
    createFuelRequest: CreateFuelRequest;
}

export interface Delete2RequestParams {
    id: number;
}

export interface Get2RequestParams {
    id: number;
}

export interface Update2RequestParams {
    id: number;
    updateFuelRequest: UpdateFuelRequest;
}


export interface FuelControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add3(requestParameters: Add3RequestParams, extraHttpRequestParams?: any): Observable<CreatedFuelResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete2(requestParameters: Delete2RequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
* @param requestParameters
     */
    get2(requestParameters: Get2RequestParams, extraHttpRequestParams?: any): Observable<GetFuelResponse>;

    /**
     * 
     * 
*/
    getAll3(extraHttpRequestParams?: any): Observable<Array<GetAllFuelResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    update2(requestParameters: Update2RequestParams, extraHttpRequestParams?: any): Observable<UpdateFuelResponse>;

}
