/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateModelRequest } from '../model/models';
import { CreatedModelResponse } from '../model/models';
import { Get400Response } from '../model/models';
import { GetAllModelResponse } from '../model/models';
import { GetModelResponse } from '../model/models';
import { Result } from '../model/models';
import { UpdateModelRequest } from '../model/models';
import { UpdateModelResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add2RequestParams {
    createModelRequest: CreateModelRequest;
}

export interface Delete1RequestParams {
    id: number;
}

export interface Get1RequestParams {
    id: number;
}

export interface Update1RequestParams {
    id: number;
    updateModelRequest: UpdateModelRequest;
}


export interface ModelControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add2(requestParameters: Add2RequestParams, extraHttpRequestParams?: any): Observable<CreatedModelResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete1(requestParameters: Delete1RequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
* @param requestParameters
     */
    get1(requestParameters: Get1RequestParams, extraHttpRequestParams?: any): Observable<GetModelResponse>;

    /**
     * 
     * 
*/
    getAll2(extraHttpRequestParams?: any): Observable<Array<GetAllModelResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    update1(requestParameters: Update1RequestParams, extraHttpRequestParams?: any): Observable<UpdateModelResponse>;

}
