/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTransmissionRequest } from '../model/models';
import { CreatedTransmissionResponse } from '../model/models';
import { Get400Response } from '../model/models';
import { GetAllTransmissionResponse } from '../model/models';
import { GetTransmissionResponse } from '../model/models';
import { Result } from '../model/models';
import { UpdateTransmissionRequest } from '../model/models';
import { UpdateTransmissionResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteRequestParams {
    id: number;
}

export interface Add1RequestParams {
    createTransmissionRequest: CreateTransmissionRequest;
}

export interface GetRequestParams {
    id: number;
}

export interface UpdateRequestParams {
    id: number;
    updateTransmissionRequest: UpdateTransmissionRequest;
}


export interface TransmissionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
* @param requestParameters
     */
    add1(requestParameters: Add1RequestParams, extraHttpRequestParams?: any): Observable<CreatedTransmissionResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    get(requestParameters: GetRequestParams, extraHttpRequestParams?: any): Observable<GetTransmissionResponse>;

    /**
     * 
     * 
*/
    getAll1(extraHttpRequestParams?: any): Observable<Array<GetAllTransmissionResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    update(requestParameters: UpdateRequestParams, extraHttpRequestParams?: any): Observable<UpdateTransmissionResponse>;

}
