export interface CarListItemDto{
    id: number,
    modelYear: number,
    plate: string,
    state: string,
    dailyPrice: number,
    color: string,
    imagePath: string,
    modelId: number,
    brandId: number,
    fuelId: number,
    transmissionId: number,
    modelName: string,
    brandName: string,
    fuelName: string,
    transmissionName: string,
    location: string,
    kilometer: number,

}